flask_wiki/forms.py
# -*- coding: utf-8 -*-
#
# This file is part of Flask-Wiki
# Copyright (C) 2020 RERO
#
# Flask-Wiki is free software; you can redistribute it and/or modify
# it under the terms of the Revised BSD License; see LICENSE file for
# more details.

"""Forms class."""

from flask_babelex import gettext as _
from flask_wtf import Form
from wtforms import TextAreaField, TextField
from wtforms.validators import InputRequired


class EditorForm(Form):
    title = TextField(_('title'), [InputRequired()])
    body = TextAreaField(_('body'), [InputRequired()])
    tags = TextField(_('tags'))

flask_wiki/__init__.py
# -*- coding: utf-8 -*-
#
# This file is part of Flask-Wiki
# Copyright (C) 2020 RERO
#
# Flask-Wiki is free software; you can redistribute it and/or modify
# it under the terms of the Revised BSD License; see LICENSE file for
# more details.

"""This extension create a wiki from a tree directory."""

from flask import current_app
import os
from .views import blueprint
from werkzeug.middleware.shared_data import SharedDataMiddleware
from . import config


class Wiki(object):
    def __init__(self, app=None):
        self.app = app
        if app is not None:
            self.init_app(app)

    def init_app(self, app):
        """Flask application initialization."""
        self.init_config(app)
        app.register_blueprint(
            blueprint,
            url_prefix=app.config.get('WIKI_URL_PREFIX')
        )
        app.add_url_rule(
            app.config.get('WIKI_URL_PREFIX') + '/files/<filename>',
            'uploaded_files', build_only=True)

        app.wsgi_app = SharedDataMiddleware(app.wsgi_app, {app.config.get(
            'WIKI_URL_PREFIX') + '/files': app.config['WIKI_UPLOAD_FOLDER']})
        app.extensions['flask-wiki'] = self

    def init_config(self, app):
        """Initialize configuration."""
        for k in dir(config):
            if k.startswith('WIKI_'):
                app.config.setdefault(k, getattr(config, k))

flask_wiki/views.py
# -*- coding: utf-8 -*-
#
# This file is part of Flask-Wiki
# Copyright (C) 2020 RERO
#
# Flask-Wiki is free software; you can redistribute it and/or modify
# it under the terms of the Revised BSD License; see LICENSE file for
# more details.

"""Views to respond to HTTP requests."""

import glob
import os
from functools import wraps

from babel import Locale
from flask import (Blueprint, abort, current_app, flash, jsonify, redirect,
                   render_template, request, url_for)
from flask.wrappers import Response
from flask_babelex import gettext as _
from werkzeug.utils import secure_filename

from .api import Processor, current_wiki, get_wiki
from .forms import EditorForm

blueprint = Blueprint(
    'wiki',
    __name__,
    template_folder='templates',
    static_folder='static'
)


# PERMISSIONS
# ===========
def can_read_permission(func):
    """Check Reading Permission."""
    @wraps(func)
    def decorated_view(*args, **kwargs):
        permission = current_app.config.get('WIKI_READ_VIEW_PERMISSION')()
        if isinstance(permission, bool):
            if not permission:
                abort(403)
            return func(*args, **kwargs)
        return permission
    return decorated_view


def can_edit_permission(func):
    """Check Edition Permission."""
    @wraps(func)
    def decorated_view(*args, **kwargs):
        permission = current_app.config.get('WIKI_EDIT_VIEW_PERMISSION')()
        if isinstance(permission, bool):
            if not permission:
                abort(403)
            return func(*args, **kwargs)
        return permission
    return decorated_view


# FILTERS
# =======
@blueprint.app_template_filter()
def prune_url(path):
    return path.replace(
        current_app.config.get('WIKI_URL_PREFIX'),
        '').strip('/')


@blueprint.app_template_filter()
def translate_ln(ln):
    return Locale(current_wiki.current_language).languages.get(ln)


@blueprint.app_template_filter()
def edit_path_list(path):
    ln = path.split('_')[-1]
    base_path = path
    if ln in current_wiki.languages:
        base_path = path.rsplit('_', 1)[0]
    return list(
        filter(
            lambda v: v['path'] != path,
            [dict(ln=ln, path='_'.join((base_path, ln)))
             for ln in current_wiki.languages]))


# PROCESSORS
# ==========
@blueprint.context_processor
def permission_processor():
    return dict(
        can_edit_wiki=current_app.config.get('WIKI_EDIT_UI_PERMISSION')(),
        can_read_wiki= current_app.config.get('WIKI_READ_UI_PERMISSION')()
    )


# MISCS
# =====
@blueprint.before_request
def setWiki():
    get_wiki()


def allowed_file(filename):
    ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


# ROUTES
# ======
@blueprint.route('/')
@can_read_permission
def index():
    return redirect(url_for('wiki.page', url=current_app.config.get('WIKI_HOME')))


@blueprint.route('/<path:url>/')
@can_read_permission
def page(url):
    page = current_wiki.get_or_404(url)
    return render_template(
        current_app.config.get('WIKI_PAGE_TEMPLATE'),
        page=page)


@blueprint.route('/edit/<path:url>/', methods=['GET', 'POST'])
@can_edit_permission
def edit(url):
    page = current_wiki.get(url)
    form = EditorForm(obj=page)
    if form.validate_on_submit():
        if not page:
            page = current_wiki.get_bare(url)
        form.populate_obj(page)
        page.save()
        flash(_('Saved'), category='success')
        return redirect(url_for('wiki.page', url=url))
    return render_template(
        current_app.config.get('WIKI_EDITOR_TEMPLATE'),
        form=form, page=page, path=url)


@blueprint.route('/preview/', methods=['POST'])
@can_edit_permission
def preview():
    data = {}
    processor = Processor(request.form['body'])
    data['html'], data['body'], data['meta'], data['toc'] = processor.process()
    return data['html']


@blueprint.route('/files', methods=['GET', 'POST'])
@can_read_permission
def files():
    if request.method == 'POST' and current_app.config['WIKI_EDIT_UI_PERMISSION']():
        # check if the post request has the file part
        if 'file' not in request.files:
            flash(_('No file part'))
            return redirect(request.url)
        file = request.files['file']
        # if user does not select file, browser also
        # submit an empty part without filename
        if file.filename == '':
            flash(_('No selected file'))
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            output_filename = os.path.join(
                current_app.config['WIKI_UPLOAD_FOLDER'], filename)
            if os.path.isfile(output_filename):
                flash(_('File already exists'), category='danger')
            else:
                file.save(output_filename)
    if request.method == 'POST' and not current_app.config['WIKI_EDIT_UI_PERMISSION']():
        flash(_('You do not have the permission to add files.'))
    files = [os.path.basename(f) for f in sorted(glob.glob(
        '/'.join([current_app.config.get('WIKI_UPLOAD_FOLDER'), '*'])), key=os.path.getmtime)]
    return render_template(
        current_app.config.get('WIKI_FILES_TEMPLATE'),
        files=files)


@blueprint.route('/search', methods=['GET'])
@can_read_permission
def search():
    query = request.args.get('q', '')
    results = current_wiki.search(query)
    return render_template(
        current_app.config.get('WIKI_SEARCH_TEMPLATE'),
        results=results, query=query)


@blueprint.errorhandler(404)
def not_found(error):
    return render_template(
        current_app.config.get('WIKI_NOT_FOUND_TEMPLATE')), 404


@blueprint.errorhandler(403)
def forbidden(error):
    return render_template(
        current_app.config.get('WIKI_FORBIDDEN_TEMPLATE')), 403

flask_wiki/templates/wiki/base.html
<!--
  This file is part of Flask-Wiki
  Copyright (C) 2020 RERO

  Flask-Wiki is free software; you can redistribute it and/or modify
  it under the terms of the Revised BSD License; see LICENSE file for
  more details
-->

{% from 'bootstrap/utils.html' import render_messages %}

<!DOCTYPE html>
<html lang="en">

<head>
  {% block head %}
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  {% block styles %}
  <!-- Bootstrap CSS -->
  {{ bootstrap.load_css() }}
  <!--font awsome -->
  <link href="{{ url_for('wiki.static', filename='css/font-awesome.min.css') }}" rel="stylesheet" />
  <link href="{{ url_for('wiki.static', filename='css/wiki.css') }}" rel="stylesheet" />
  {% endblock %}

  <title>{{ _('Flask-Wiki') }}</title>
  {% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand navbar-light bg-light">
    <a class="navbar-brand" href="#">{{ _('Flask-Wiki') }}</a>
  </nav>

  <div class="container py-4">
    {{ render_messages(dismissible=True, dismiss_animate=True) }}
    {% block navigation %} {%- include "wiki/navigation.html" %} {% endblock %}
    {% block content %} {% endblock %}
  </div>

  <footer class="container py-5">
    <div class="row">
      <div class="col-md-6">
        <small class="d-block mb-3 text-muted">RERO &copy; 2020</small>
      </div>
      <div class="col-md-6">
        {% for language in g._wiki.languages -%}
        <a class="ml-2" href="">{{ language }}</a>
        {%- endfor %}
      </div>
    </div>
  </footer>

  {% block scripts %}
  <!-- Optional JavaScript -->
  {{ bootstrap.load_js() }}
  <script type="text/javascript" src="{{ url_for('wiki.static', filename='js/wiki.js') }}"></script>
  {% endblock %}
</body>

</html>

flask_wiki/templates/wiki/editor.html
<!--
  This file is part of Flask-Wiki
  Copyright (C) 2020 RERO

  Flask-Wiki is free software; you can redistribute it and/or modify
  it under the terms of the Revised BSD License; see LICENSE file for
  more details
-->

{% from 'bootstrap/form.html' import render_form_row %}

{% extends config.get('WIKI_BASE_TEMPLATE') %}
{% set active_page = "editor" %}

{% block content %}
<div class="wiki-editor">
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" id="edit-tab" href="#edit" role="tab" aria-controls="home"
        aria-selected="true">{{ _('Edit') }}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" id="preview-tab" href="#preview" role="tab"
        data-preview-url="{{ url_for('wiki.preview') }}" aria-controls="profile"
        aria-selected="false">{{ _('Preview') }}</a>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane fade show active" id="edit" role="tabpanel" aria-labelledby="home-tab">
      <form class="editor" method="post">

        {{ form.csrf_token() }}
        {{ render_form_row([form.title, form.tags]) }}
        {{ render_form_row([form.body]) }}
        <button class="btn btn-sm btn-outline-primary" type="submit">{{ _('Save') }}</button>
        {%- set pathes = path | edit_path_list -%}
        {%- if pathes %}
        <div class="btn-group">
          <button type="button" class="btn btn-outline-primary btn-sm">{{ _('Edit in') }}</button>
          <button type="button" class="btn btn-outline-primary btn-sm dropdown-toggle dropdown-toggle-split"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          </button>
          <div class="dropdown-menu">
            {%- for path in pathes %}
            <a class="dropdown-item" href="{{ url_for('wiki.edit', url=path.path) }}">{{ path.ln | translate_ln }}</a>
            {%- endfor -%}
          </div>
        </div>
        {%- endif -%}
      </form>
    </div>
    <div class="tab-pane fade" id="preview" role="tabpanel" aria-labelledby="profile-tab"></div>
  </div>
</div>

{% endblock %}

flask_wiki/templates/wiki/files.html
<!--
  This file is part of Flask-Wiki
  Copyright (C) 2020 RERO

  Flask-Wiki is free software; you can redistribute it and/or modify
  it under the terms of the Revised BSD License; see LICENSE file for
  more details
-->

{% extends config.get('WIKI_BASE_TEMPLATE') %}
{% set active_page = "files" %}

{% block content %}
<div class="wiki-files">
    <div data-delay="1500" class="toast">

        <div class="toast-header text-primary font-weight-bold">
            Markdown
        </div>
        <div class="toast-body">
            {{ _('Copied in you clipboard') }}
        </div>
    </div>

    {% if can_edit_wiki %}
    <form class="float-right" method="post" enctype="multipart/form-data">
        <div class="custom-file">
            <button class="btn btn-outline-primary btn-sm">{{ _('Upload a file') }}</button>
            <input class="custom-file-input" type="file" name="file" accept="image/*" />
        </div>
    </form>
    {% endif %}

    <h1>{{ _('List of Uploaded Files') }}</h1>
    {% for file in files %}
    <figure class="figure ml-4">
        <img src="{{ url_for('uploaded_files', filename=file) }}" class="figure-img img-fluid rounded img-thumbnail"
            alt="{{ file }}" />
        <figcaption class="figure-caption text-center">
            <a href="{{ url_for('uploaded_files', filename=file) }}">{{ file }}</a>
            <button data-name="{{ file }}"
                data-link="{{ url_for('uploaded_files', filename=file) }}" class="copy-md-code btn btn-sm btn-outline-primary">
                <i class="fa fa-clipboard"></i>
            </button>
        </figcaption>
    </figure>
    {% endfor %}
</div>
{% endblock %}

flask_wiki/templates/wiki/navigation.html
<!--
  This file is part of Flask-Wiki
  Copyright (C) 2020 RERO

  Flask-Wiki is free software; you can redistribute it and/or modify
  it under the terms of the Revised BSD License; see LICENSE file for
  more details
-->

<nav class="navbar navbar-expand navbar-light bg-light row mb-4">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('wiki.index') }}">{{ _('Home') }}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('wiki.files') }}">{{ _('Files') }}</a>
    </li>
  </ul>
  <form class="form-inline ml-auto" action="{{ url_for('wiki.search') }}">
    <input class="form-control mr-sm-2" type="search" value="{{ query }}" name="q" placeholder="{{ _('Search') }}"
      aria-label="{{ _('Search') }}" />
    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">
      {{ _('Search') }}
    </button>
  </form>
</nav>

flask_wiki/templates/wiki/page.html
<!--
  This file is part of Flask-Wiki
  Copyright (C) 2020 RERO

  Flask-Wiki is free software; you can redistribute it and/or modify
  it under the terms of the Revised BSD License; see LICENSE file for
  more details
-->

{% extends config.get('WIKI_BASE_TEMPLATE') %}
{% set active_page = "page" %}

{% block content %}
<div class="row mt-4 wiki-page">
    <div class="col-md-8">
        {% if can_edit_wiki %}
        <a class="btn btn-outline-primary btn-sm float-right" href="{{ url_for('wiki.edit', url=page.url) }}">Edit</a>
        {% endif %}
        <h5>{{page.title}}</h5>
        {% for tag in page.tags.split(',') %}
        <span class="badge badge-primary">{{ tag }}</span>
        {% endfor %}
        <hr>
        {{ page }}
    </div>
    <div class="col-md-4">
        <h5>{{ _('Table of Content') }}</h5>
        {{ page.toc }}
    </div>
</div>
{% endblock %}

flask_wiki/templates/wiki/search.html
<!--
  This file is part of Flask-Wiki
  Copyright (C) 2020 RERO

  Flask-Wiki is free software; you can redistribute it and/or modify
  it under the terms of the Revised BSD License; see LICENSE file for
  more details
-->

{% from 'bootstrap/form.html' import render_form_row %}

{% extends config.get('WIKI_BASE_TEMPLATE') %}
{% set active_page = "search" %}

{% block content %}
{{ results | length }} {{ _('results') }}

<ul class="list-group list-group-flush">
  {%- for result in results -%}
  <li class="list-group-item ">
    <a class="mr-2" href="{{ url_for('wiki.page', url=result.url) }}">
      {{ result.title }}
    </a>
    {% for tag in result.tags.split(',') %}
    <span class="badge badge-primary">{{ tag }}</span>
    {% endfor %}
  </li>
  {%- endfor -%}
</ul>

{% endblock %}